apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: product-listings-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: product-listings-manager
    app.kubernetes.io/part-of: product-listings-manager
  name: product-listings-manager
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: product-listings-manager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: product-listings-manager
    spec:
      containers:
      - env:
        - name: SQLALCHEMY_DATABASE_URI
          value: 'sqlite://:memory:'
        image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
