apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: product-listings-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: product-listings-manager
    app.kubernetes.io/part-of: product-listings-manager
  name: product-listings-managerxaru
spec:
  port:
    targetPort: 5000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: product-listings-manager
    weight: 100
status: {}
